language: cpp

compiler:
    - clang
    - gcc

install:
    - scripts/install_compilers.sh
    - sudo apt-get install liblapack-dev
    - scripts/install_armadillo.sh
    - scripts/install_figtree.sh

script:
    - scripts/build_and_test.sh
