language: cpp

compiler:
    - clang
    - gcc

env:
    - CPD_64BIT=true
    - CPD_64BIT=false

install:
    - scripts/install_compilers.sh
    - sudo apt-get install liblapack-dev libarpack2-dev libsuperlu3-dev gfortran
    - scripts/install_armadillo.sh
    - scripts/install_figtree.sh
    - sudo pip install cpp-coveralls

script:
    - scripts/build_and_test.sh
