language: cpp

compiler:
    - clang
    - gcc

env:
    - CPD_64BIT=true
    - CPD_64BIT=false

install:
    - scripts/install_compilers.sh
    - sudo apt-get install liblapack-dev libarpack2-dev libsuperlu3-dev gfortran
    - scripts/install_armadillo.sh
    - scripts/install_figtree.sh
    - sudo pip install cpp-coveralls

before_script:
    - if [[ $CXX == "g++" ]]; then
      export CPD_BUILD_COVERAGE="ON";
      export CXX="g++-4.8";
      else
      export CPD_BUILD_COVERAGE="OFF";
      fi

script:
    - scripts/build_and_test.sh

after_script:
    - scripts/coveralls.sh
