language: cpp

compiler:
    - clang
    - gcc

env:
    - CPD_64BIT=true CPD_USE_ARMA_WRAPPER=true
    - CPD_64BIT=true CPD_USE_ARMA_WRAPPER=false
    - CPD_64BIT=false CPD_USE_ARMA_WRAPPER=true
    - CPD_64BIT=false CPD_USE_ARMA_WRAPPER=false

install:
    - make -f dependencies.mak install-on-ubuntu
    - sudo pip install cpp-coveralls

before_script:
    - if [[ $CXX == "g++" ]]; then
      export CPD_BUILD_COVERAGE="ON";
      export CXX="g++-4.8";
      else
      export CPD_BUILD_COVERAGE="OFF";
      fi

script:
    - scripts/build_and_test.sh

after_script:
    - if [[ $CPD_BUILD_COVERAGE == "ON" ]]; then
      scripts/coveralls.sh;
      fi
