language: cpp

compiler:
    - clang
    - gcc

env:
    - ARMA_64BIT_WORD=ON
    - ARMA_64BIT_WORD=OFF

install:
    - make -f make/dependencies.mak install-build-system-apt-precise
    - if [[ $CXX == "g++" ]]; then
      export CPD_BUILD_COVERAGE="ON";
      export CXX="g++-4.8";
      sudo pip install cpp-coveralls;
      else
      export CPD_BUILD_COVERAGE="OFF";
      fi
    - make -f make/dependencies.mak install-dependencies-apt-general

script:
    - scripts/build_and_test.sh

after_script:
    - if [[ $CPD_BUILD_COVERAGE == "ON" ]]; then
      scripts/coveralls.sh;
      fi
