language: cpp

compiler:
    - clang
    - gcc

install:
    - sudo apt-get install libopenblas-dev liblapack-dev libarpack++2-dev
    - scripts/install_armadillo.sh
    - scripts/install_figtree.sh

script:
    - scripts/build_and_test.sh
